// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Car recommendation AI agent.
 *
 * - recommendCars - A function that recommends cars based on user preferences.
 * - CarRecommendationInput - The input type for the recommendCars function.
 * - CarRecommendationOutput - The return type for the recommendCars function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CarRecommendationInputSchema = z.object({
  preferences: z
    .string()
    .describe(
      'The user preferences for a car rental, described in their own words (e.g., fuel-efficient for a long trip with four passengers).'
    ),
});
export type CarRecommendationInput = z.infer<typeof CarRecommendationInputSchema>;

const CarRecommendationOutputSchema = z.object({
  carRecommendations: z
    .array(z.string())
    .describe('A list of car model recommendations based on the user preferences.'),
});
export type CarRecommendationOutput = z.infer<typeof CarRecommendationOutputSchema>;

export async function recommendCars(input: CarRecommendationInput): Promise<CarRecommendationOutput> {
  return recommendCarsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'carRecommendationPrompt',
  input: {schema: CarRecommendationInputSchema},
  output: {schema: CarRecommendationOutputSchema},
  prompt: `You are a car rental expert.  Based on the user's stated preferences, recommend a list of car models that would be suitable for them.

User Preferences: {{{preferences}}}

Car Recommendations:`, // The prompt should end with the field the LLM needs to fill in.
});

const recommendCarsFlow = ai.defineFlow(
  {
    name: 'recommendCarsFlow',
    inputSchema: CarRecommendationInputSchema,
    outputSchema: CarRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
